# Generated by Django 5.0 on 2023-12-30 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='restaurant_profile_pics/')),
                ('tag1', models.CharField(blank=True, choices=[('Free delivery', 'Free delivery'), ('Buy 2 get 1 free', 'Buy 2 get 1 free')], max_length=50, null=True)),
                ('tag2', models.CharField(blank=True, choices=[('Free delivery', 'Free delivery'), ('Buy 2 get 1 free', 'Buy 2 get 1 free')], max_length=50, null=True)),
                ('stars', models.FloatField(default=0)),
                ('stars_count', models.IntegerField(default=0)),
                ('distance', models.FloatField(default=0)),
                ('category', models.CharField(choices=[('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Pie', 'Pie'), ('Asian', 'Asian'), ('Desserts', 'Desserts'), ('Skewers', 'Skewers'), ('Rice', 'Rice'), ('Vegetables', 'Vegetables'), ('Other', 'Other')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('courier_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('opening_time', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(24)])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='address.address')),
            ],
        ),
    ]
