# Generated by Django 5.0 on 2024-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='stars',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='stars_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
