# Generated by Django 5.0 on 2023-12-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('restaurant', '0002_alter_restaurant_address'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_foods',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='food.food'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='restaurant.restaurant'),
        ),
    ]
