# Generated by Django 4.2.7 on 2024-01-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_max_time_to_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='max_time_to_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='min_time_to_delivery',
            field=models.IntegerField(default=0),
        ),
    ]
