# Generated by Django 4.2.7 on 2024-01-23 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_food_price_alter_food_stars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='stars_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
