# Generated by Django 4.2.7 on 2024-01-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_courier_price_and_more'),
        ('order', '0003_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
